views:
  - title: Home
    cards:
      - type: entities
        entities:
          - entity: input_select.set_sg_start_stop_mode
          - entity: sensor.sungrow_inverter_state
        title: Inverter State
      - type: entities
        entities:
          - entity: input_number.set_sg_min_soc
          - entity: input_number.set_sg_max_soc
          - entity: sensor.min_soc
          - entity: sensor.max_soc
          - entity: input_select.set_sg_ems_mode
          - entity: sensor.sungrow_ems_mode_selection
          - entity: input_select.set_sg_battery_forced_charge_discharge_cmd
          - entity: sensor.battery_forced_charge_discharge_cmd_raw
          - entity: sensor.sungrow_battery_forced_charge_discharge_cmd
          - entity: input_number.set_sg_forced_charge_discharge_power
          - entity: sensor.battery_forced_charge_discharge_power
          - entity: input_number.set_sg_batt_soc_reserve
          - entity: sensor.battery_soc_reserve
          - entity: sensor.battery_max_charge_power
          - entity: input_number.set_sg_battery_max_charge_power
          - entity: sensor.battery_max_discharge_power
          - entity: input_number.set_sg_battery_max_discharge_power
        title: EMS
title: PV Control
